### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Titeinohito** [Titeinohito/furima-35803#11]
# URL
https://furima-35803.herokuapp.com/
# Basic認証IDとPassword
ID: admin
Password: 2222
# 出品者用のメールアドレスとパスワード
mail: test@testuser1
Password: 12345a
# 購入者用のメールアドレスとパスワード
mail: test@testuser2
Password: 12345b

**Comment by takumi0530** [comment]
@Titeinohito さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **本番環境で投稿した商品画像が、S3に保存されること**
herokuにて保存されておりましたのでご確認をお願いいたします。

- [x] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**

- [x] **エラーハンドリングができていること（入力に問題がある状態で「購入」ボタンが押された場合、情報は受け入れられず、購入ページでエラーメッセージが表示されること）**
情報を埋めても埋めなくても、購入ボタンを押すとエラーページに遷移してしまいました。
**※上記により、購入機能・売却後の動作確認ができておりません。次回ご提出時に確認させていただきます。**
<img width="583" alt="スクリーンショット 2021-08-17 11 48 53" src="https://user-images.githubusercontent.com/76197191/129656118-0706e102-6d64-4cfe-a67e-702dd39ff0a7.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@Titeinohito さん、お待たせいたしました。再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/129669350-811f35c0-b1de-4944-9a75-563eb99f50f8.png)
